apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo.aerogramme.io
spec:
  duration: 2160h   # 90d
  renewBefore: 360h # 15d
  secretName: demo.aerogramme.io
  dnsNames:
    - demo.aerogramme.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer