apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-secret
spec:
  secretName: acme-crt-secret
  dnsNames:
    - wordpress.aerogramme.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer